name: Deploy Toolkit 2

on:
  push:
    branches:
      - staging-internal
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy_staging:
    if: github.ref == 'refs/heads/staging-internal'
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: deploy-staging-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    permissions:
      contents: read
      pages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R and Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libudunits2-dev libgdal-dev
          sudo apt-get install libmagick++-dev

      - name: Install R packages
        run: |
          R -e 'install.packages(c("bookdown", "rmarkdown", "plotly", "shiny", "tidycensus", "tidyverse", "viridis", "ggmap", "ggplot2", "maps", "dplyr", "knitr", "latticeExtra", "pals", "classInt", "sf", "udunits2", "tmap", "lubridate", "gifski", "magick", "cowplot"))'
          R -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager"); BiocManager::install("Biobase")'

      - name: Build site for staging branch
        run: R -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book  # Directory where bookdown outputs the HTML files
          cleanup: false  # Keep existing files in the branch